version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install -y ansible
      - run:
          name: Run Ansible Playbook on localhost
          command: |
            echo "✅ 변경 사항이 푸시되었습니다. Ansible을 로컬에서 실행하세요."

workflows:
  deploy-on-push:
    jobs:
      - deploy
